[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
stature = "9VFHpUQnHsG94AKzGfzf4mAeunxcQw8G9am6FfVEBVZb"

[programs.localnet]
stature = "4h5eesi3oxqnJCXUKN9TZ2y23vqkAZkSg9WAb4hWa4mG"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
