[package]
name = "stature"
version = "0.1.0"
description = "A simple SOL stature program"
edition = "2021"


[lib]
crate-type = ["cdylib", "lib"] # "lib" allows other programs to import it
name = "stature"

[features]
default = []
cpi = ["no-entrypoint"] # When contract282 imports this, it uses "cpi"
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
custom-heap = []
custom-panic = []
anchor-debug = []



# [lints.rust]
# unexpected_cfgs = { level = "warn", check-cfg = [
#     'cfg(target_os, values("solana"))',
#     'cfg(feature, values("anchor-debug", "custom-heap", "custom-panic"))',
# ] }
[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }

[dev-dependencies]
# Force everything to the 3.0.x branch to match your solana-cli 3.1
solana-sdk = "=3.0.0"
solana-program-pack = "=3.0.0"
solana-system-interface = "=3.0.0"
# If litesvm is causing the bloat, try updating it or temporary commenting it out
litesvm = "0.9.1"